### ISSUE TITLE
New streamstats s3 Streamstats-setup bucket

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats-Tools#10]
When you have a chance could you create a new S3 bucket named Streamstats-setup, for server setup items.

**Comment by aaronstephenson** [comment]
Bucket `streamstats-setup` created, WIM Power Users have same permissions to it as all the other buckets.

**Comment by HansVraga** [comment]
@kjacobsen16 like in #11 can you confirm this is done and close if so?
