### ISSUE TITLE
GIS - write access to test-data folder in streamstats-staged-data bucket

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats-Tools#11]
Will you please give GIS users write access to test-data folder located in streamstats-staged-data bucket.
Purpose of this folder is to allow gis users a place to write files while trying out the scripts.

-> we should probably remove write access to data folder for now, until later.

**Comment by aaronstephenson** [comment]
Done.

**Comment by jknewson** [comment]
@aaronstephenson the access rights aren't working for the GIS team.

**Comment by aaronstephenson** [comment]
@jknewson could you be more specific? I can't really troubleshoot without more information.

**Comment by aaronstephenson** [comment]
For whatever reason, the change I made to the IAM policy two weeks ago never actually "took". So I just made the change again, saved it, and confirmed the change is in the policy.

Please try again,

**Comment by HansVraga** [comment]
Going to assign this to @kjacobsen16 as she's working with the GIS team and can verify access is in order, and close if so.

**Comment by HansVraga** [comment]
Appears this work is done.
