### ISSUE TITLE
Long Term Goals

### ISSUE THREAD

**Issue by kjacobsen16** [USGS-WiM/StreamStats-Tools#15]
**Won't fix-** [ ] have environment for GIS people to work on regional data using cheaper storage, possibly an instance for each state, can shut down when not using

- [x] write script to pull down region data, clean it when pulling down rather than when pushing it up

- [x] change structure of data so all regional data is together in one folder (rather than data, schema, xml) -- should discuss w/ Ryan and Kitty

**Comment by kjacobsen16** [comment]
@HansVraga are we still thinking about creating a separate environment for when people need to edit states?

**Comment by HansVraga** [comment]
That's something we can table. Let's `wont fix` that one and close this.

**Comment by HansVraga** [comment]
Development of tools for use in separate GIS workspace environments put on hold in favor of other StreamStats priorities. Will be picked back up in a separate ticket as priorities dictate.
