### ISSUE TITLE
XML trims out global parameters

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats-Tools#17]
The GlobalParameters xml node is required to aggregate the local and global basins for streamstats. Looks like the xml trim method cuts it out. Attached is a comparison of the previous to current xml (red is cut
[XML_SD_diff.pdf](https://github.com/USGS-WiM/StreamStats-Tools/files/3152595/XML_SD_diff.pdf)

![image](https://user-images.githubusercontent.com/8713714/57299185-2aac1400-7091-11e9-81fd-52e32d6c128e.png)

**Comment by kjacobsen16** [comment]
fixed
