### ISSUE TITLE
xml Projection path redirect

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats-Tools#21]
Some state XML's (PA, NY, OH... and a few others) contain a projection path. During the xml clean, the path needs to be redirected from e:\schemas\... to e:\projections folder. below is a dirty version of the xml for PA for example, (line 59 in xml)

` <ApField AdditionalParams="FORMAT=0.0;COMPMETHOD=CUSTTYPE;CUSTOPNAME=ESRI.APWR.WshpTools.CentroidXOp;PROJECTIONFILENAME=e:\schemas\PA_ss.prj" AliasName="CENTROXA83" AllowNull="1" Decimals="2" Desc="X coordinate of the centroid, in NAD_1983_Albers, meters" FieldWidth="10" Name="CENTROXA83" TagName="CENTROXA83" Type="3">`

Needs to be converted to 
` <ApField AdditionalParams="FORMAT=0.0;COMPMETHOD=CUSTTYPE;CUSTOPNAME=ESRI.APWR.WshpTools.CentroidXOp;PROJECTIONFILENAME=e:\projections\PA_ss.prj" AliasName="CENTROXA83" AllowNull="1" Decimals="2" Desc="X coordinate of the centroid, in NAD_1983_Albers, meters" FieldWidth="10" Name="CENTROXA83" TagName="CENTROXA83" Type="3">`

**Comment by kjacobsen16** [comment]
done
