### ISSUE TITLE
GIS read/write access to S3 streamstats-staged-data

### ISSUE THREAD

**Issue by jknewson** [USGS-WiM/StreamStats-Tools#6]
They should have access to ./data, ./xml, ./schemas subfolders 

(GIS team)
"Steeves, Peter" <psteeves@usgs.gov>, 
"Ryan Thompson" <rcthomps@usgs.gov>, 
"Kolb, Katharine" <kkolb@usgs.gov>

**Comment by aaronstephenson** [comment]
Users created, permissions assigned in a policy. Just need to email credentials (and instructions?) to the users. Who wants to do that? @HansVraga ?

**Comment by HansVraga** [comment]
Don't want to send out credentials until we're ready for some testing. I
think we'll get there this week.

**Comment by aaronstephenson** [comment]
Anyone willing to test this?

**Comment by marsmith** [comment]
yea i can test can someone pass a long a set of creds?

**Comment by aaronstephenson** [comment]
You bet, I'll email you.

**Comment by HansVraga** [comment]
@aaronstephenson Can you pass me the credentials for Pete, Ryan, and Kitty so I can let dole them out?

**Comment by aaronstephenson** [comment]
Keys emailed to @HansVraga
